name: Deploy to Production

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Create deployment directory
      run: |
        mkdir -p deployment
        cp docker-compose.yml deployment/
        cp .env.sample deployment/.env

    - name: Configure environment
      run: |
        cd deployment
        # Replace with actual production values
        sed -i 's/POSTGRES_PASSWORD=postgres/POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}/' .env
        sed -i 's/JWT_SECRET=change-me/JWT_SECRET=${{ secrets.JWT_SECRET }}/' .env

    - name: Deploy with Docker Compose
      run: |
        cd deployment
        echo "🚀 Deploying to ${{ github.event.inputs.environment || 'production' }}"
        # In a real deployment, you would:
        # 1. Copy files to your server
        # 2. Run docker-compose up -d
        # 3. Run database migrations
        # 4. Perform health checks
        echo "✅ Deployment completed successfully"

    - name: Run health checks
      run: |
        echo "🔍 Running health checks..."
        # Add actual health check commands here
        echo "✅ All health checks passed"

    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi
